### ISSUE TITLE
syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by NavaneethVijay** [OptimoApps/razorpay-x#2]
### syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) while creating a new contact.

````
$contact = new Contact(); 
$contact->name = $user->name;
$contact->email = $user->email;
$contact->type = ContactTypeEnum::customer;
$response = RazorPayXFacade::contact()->create($contact);
````

![Screenshot from 2020-07-16 13-56-59](https://user-images.githubusercontent.com/33292252/87646309-49fe0100-c76c-11ea-9ea4-37b25117c5a5.png)

**Comment by ssatz** [comment]
Thanks for using the package. Please check facade , it should be **RazorPayX**

```$contact = new Contact(); 
$contact->name = $user->name;
$contact->email = $user->email;
$contact->type = ContactTypeEnum::customer;
$response = RazorPayX::contact()->create($contact);```

**Comment by NavaneethVijay** [comment]
@ssatz the facade is correct, apparently my php version is 7.4 in my server and laravel was not using this version hence the syntax public string $id was invalid,  `"php": "^7.4",` was included in `composer.json` file and the issue was resolved.

**Comment by ssatz** [comment]
@NavaneethVijay Glad that you have solved the issue. I am closing now, you can reopen or create a new issue if required.
